// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7BJiwIa7J2llFnmYe-eHTtKJi11gnBxc',
    appId: '1:162564554099:web:7d8d43779925e659d1d906',
    messagingSenderId: '162564554099',
    projectId: 'heimdall-5aecb',
    authDomain: 'heimdall-5aecb.firebaseapp.com',
    storageBucket: 'heimdall-5aecb.appspot.com',
    measurementId: 'G-YJY39SDG6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVWXtVDuqS4RHmzm8ujqrZOhgLTX-nYEs',
    appId: '1:162564554099:android:b9e5b2719f2b7a36d1d906',
    messagingSenderId: '162564554099',
    projectId: 'heimdall-5aecb',
    storageBucket: 'heimdall-5aecb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Co2tw72sqkkvuNuHMaaYsUibxPOFN60',
    appId: '1:162564554099:ios:238b0db27827126fd1d906',
    messagingSenderId: '162564554099',
    projectId: 'heimdall-5aecb',
    storageBucket: 'heimdall-5aecb.appspot.com',
    iosBundleId: 'com.example.heimdall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Co2tw72sqkkvuNuHMaaYsUibxPOFN60',
    appId: '1:162564554099:ios:e3294752ddc8bc30d1d906',
    messagingSenderId: '162564554099',
    projectId: 'heimdall-5aecb',
    storageBucket: 'heimdall-5aecb.appspot.com',
    iosBundleId: 'com.example.heimdall.RunnerTests',
  );
}
